In [113]:
import pandas as pd
import numpy as np

In [114]:
df=pd.read_csv("flats.csv")

In [115]:
pd.set_option("display.max_rows",None)

In [116]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [117]:
df = df.drop(columns = ["link"])

In [118]:
df["society"]=df["society"].str.lower()

In [119]:
len(df["society"].value_counts())

632

In [120]:
import re

In [121]:
####.value_counts
#df["society"].apply(lambda x: re.sub(r"\d+\.\d+\s?★$","",str(x)))
#len(df["society"].apply(lambda x: re.sub(r'\d+(\.\d+)?\s?★',"",str(x)).strip()
df["society"]=df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [122]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [123]:
df["price"].value_counts()

1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
1.85 Crore          23
2.35 Crore          23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
3.4 Crore           14
2.15 Crore          14
2.45 Crore          14
1.32 Crore          13
82 Lac              13
78 Lac              13
38 Lac              13
3.25 Crore          13
2.7 Crore           13
92 Lac              13
42 Lac              12
5 Crore             12
1.95 Crore          12
1.42 Crore          12
2.8 Crore           12
32 Lac              11
Price on Request    11
88 Lac              11
1.08 Crore          11
25 Lac              11
26 Lac              10
1.78 Crore          10
87 Lac              10
1.12 Crore          10
28 Lac              10
1.28 Crore          10
2.55 Crore          10
2.05 Crore           9
36 Lac               9
2.85 Crore           9
3.45 Crore           9
1.72 Crore           9
99 Lac               9
22 Lac               9
4 Crore              9
1.68 Crore           9
27 Lac               8
1.54 Crore           8
3.2 Crore            8
98 Lac               8
1.76 Crore           8
6 Crore              8
86 Lac               8
56 Lac               8
6.5 Crore            8
48 Lac               8
4.25 Crore           8
2.75 Crore           8
1.18 Crore           8
20 Lac               8
1.26 Crore           8
97 Lac               7
3.3 Crore            7
3.7 Crore            7
72 Lac               7
1.27 Crore           7
1.19 Crore           7
1.36 Crore           7
2.9 Crore            7
1.02 Crore           7
46 Lac               7
39 Lac               7
1.99 Crore           7
1.29 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.01 Crore           6
1.49 Crore           6
1.98 Crore           6
3.9 Crore            6
3.65 Crore           6
37 Lac               6
5.5 Crore            6
1.07 Crore           6
21 Lac               6
2.95 Crore           6
96 Lac               6
1.16 Crore           6
1.13 Crore           6
1.34 Crore           6
54 Lac               6
3.35 Crore           6
1.51 Crore           6
1.14 Crore           6
3.05 Crore           6
4.1 Crore            6
1.39 Crore           6
71.5 Lac             6
1.17 Crore           5
1.92 Crore           5
3.75 Crore           5
2.22 Crore           5
6.75 Crore           5
1.44 Crore           5
1.24 Crore           5
1.69 Crore           5
1.82 Crore           5
49 Lac               5
1.33 Crore           5
2.78 Crore           5
1.91 Crore           5
1.43 Crore           5
66 Lac               5
1.83 Crore           5
1.47 Crore           5
29 Lac               5
4.5 Crore            5
2.12 Crore           5
2.29 Crore           5
93 Lac               5
1.62 Crore           5
68 Lac               5
64 Lac               5
1.79 Crore           5
1.93 Crore           5
24 Lac               5
41.5 Lac             4
5.6 Crore            4
1.52 Crore           4
1.23 Crore           4
1.22 Crore           4
4.3 Crore            4
28.5 Lac             4
2.09 Crore           4
62 Lac               4
1.73 Crore           4
5.25 Crore           4
67 Lac               4
58 Lac               4
1.37 Crore           4
74 Lac               4
1.31 Crore           4
1.58 Crore           4
6.15 Crore           4
3.95 Crore           4
3.6 Crore            4
1.77 Crore           4
5.9 Crore            4
7 Crore              4
73 Lac               4
89 Lac               4
1.48 Crore           4
1.71 Crore           4
33 Lac               4
31 Lac               4
4.85 Crore           4
1.64 Crore           4
1.66 Crore           4
36.5 Lac             4
3.1 Crore            4
52 Lac               3
2.01 Crore           3
51 Lac               3
2.08 Crore           3
1.41 Crore           3
83 Lac               3
94 Lac               3
2.24 Crore           3
3.49 Crore           3
2.51 Crore           3
1.67 Crore           3
47 Lac               3
1.21 Crore           3
4.8 Crore            3
4.75 Crore           3
2.36 Crore           3
72.5 Lac             3
1.04 Crore           3
64.5 Lac             3
2.79 Crore           3
2.33 Crore           3
1.88 Crore           3
5.8 Crore            3
3.85 Crore           3
91 Lac               3
1.09 Crore           3
1.63 Crore           3
2.03 Crore           3
4.2 Crore            3
3.15 Crore           3
34 Lac               3
1.57 Crore           3
3.8 Crore            3
69 Lac               3
2.28 Crore           3
84 Lac               3
8 Crore              2
2.23 Crore           2
53 Lac               2
2.17 Crore           2
27.1 Lac             2
77.5 Lac             2
8.5 Crore            2
2.14 Crore           2
6.2 Crore            2
2.52 Crore           2
53.5 Lac             2
2.58 Crore           2
4.49 Crore           2
1.46 Crore           2
4.26 Crore           2
2.57 Crore           2
2.99 Crore           2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
2.41 Crore           2
5.2 Crore            2
2.02 Crore           2
14 Crore             2
2.87 Crore           2
2.26 Crore           2
56.2 Lac             2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.13 Crore           2
4.55 Crore           2
2.04 Crore           2
25.5 Lac             2
27.75 Lac            2
4.45 Crore           2
11 Crore             2
4.7 Crore            2
7.5 Crore            2
88.5 Lac             2
37.1 Lac             1
54.8 Lac             1
63.4 Lac             1
2.38 Crore           1
2.64 Crore           1
3.98 Crore           1
4.02 Crore           1
7.4 Crore            1
97.5 Lac             1
39.5 Lac             1
2.06 Crore           1
2.07 Crore           1
64.45 Lac            1
44 Lac               1
2.49 Crore           1
3.78 Crore           1
2.92 Crore           1
9 Crore              1
61 Lac               1
4.21 Crore           1
89.77 Lac            1
4.16 Crore           1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
68.85 Lac            1
4.52 Crore           1
1.84 Crore           1
8.44 Crore           1
1.97 Crore           1
82.5 Lac             1
13.2 Crore           1
98.88 Lac            1
3.99 Crore           1
37.5 Lac             1
2.32 Crore           1
2.44 Crore           1
57 Lac               1
1.74 Crore           1
95.5 Lac             1
94.5 Lac             1
2.96 Crore           1
29.8 Lac             1
6.02 Crore           1
96.07 Lac            1
7.9 Crore            1
32.5 Lac             1
3.23 Crore           1
19 Lac               1
70.85 Lac            1
97.04 Lac            1
40.3 Lac             1
3.72 Crore           1
88.4 Lac             1
94.99 Lac            1
1.53 Crore           1
7.52 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
2.69 Crore           1
86.99 Lac            1
9.95 Crore           1
86.92 Lac            1
9.2 Crore            1
49.5 Lac             1
2.54 Crore           1
16 Lac               1
7.8 Crore            1
2.86 Crore           1
15 Crore             1
4.4 Crore            1
9.3 Crore            1
5.3 Crore            1
4.95 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
2.72 Crore           1
98.1 Lac             1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
11.25 Crore          1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
price                1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
55.6 Lac             1
2.63 Crore           1
5.15 Crore           1
47.5 Lac             1
1.06 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
2.77 Crore           1
55.5 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
9.14 Crore           1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
62.5 Lac             1
Name: price, dtype: int64

In [124]:
df = df[~(df["price"]=="Price on Request")]

In [125]:
def price_con(val):
    if type(val)==float:
        return val
    elif isinstance(val, list) and len(val) >= 2:
        if val[1] == "Lac":
            return round(float(val[0])/100,2)
        else:
            return round(float(val[0]),2)

In [126]:
df["price"]=df["price"].str.split(" ").apply(price_con)

In [127]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [128]:
df["area"]=df["area"].str.split("/").str.get(0).str.replace("₹","").str.replace(",","").str.strip()

In [129]:
df.drop(286,inplace = True)

In [130]:
df["area"]=df["area"].astype("float")

In [131]:
df=df.rename(columns = {"area":"persf_area","bedRoom":"bedroom"})

In [132]:
df.head()

,property_name,society,price,persf_area,areaWithType,bedroom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [133]:
df["bedroom"]=df["bedroom"].str.split().str.get(0).str.strip().astype("float")

In [134]:
df[df.bedroom.isnull()].index

Int64Index([2850, 2851, 2852, 2853, 2923, 2924, 2925, 2927, 2928, 2994, 2995,
            2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003],
           dtype='int64')

In [135]:
df = df.drop(df[df.bedroom.isnull()].index)

In [136]:
df["bathroom"]=df["bathroom"].str.split().str.get(0).str.strip().astype("float")

In [137]:
df["balcony"]=df["balcony"].str.split().str.get(0).str.replace("No","").str.strip()

In [138]:
df["balcony"]

0        1
1        1
2        3
3        2
4        3
5        3
6        3
7        3
8       3+
9        2
10       2
11       1
12       3
13      3+
14       3
15       3
16
17       2
18       3
19       3
20       2
21      3+
22       3
23      3+
24      3+
26       1
27       2
28      3+
29       2
30
31       2
32      3+
33       1
34       2
35       3
36      3+
37       2
38       2
39       3
40       2
41      3+
42      3+
43      3+
44       2
45      3+
46      3+
47       2
48      3+
49      3+
50      3+
51       2
52       3
53       2
54       2
55      3+
56       1
57       1
58       1
59       2
60       2
61       3
62      3+
63       2
64      3+
65       3
66      3+
67       3
68       2
69       2
70       3
71       3
72       2
73       1
74       3
75       2
76       2
77       3
78      3+
79       3
80       2
81
82       1
83      3+
84       1
85       1
86      3+
87       1
88       1
89       1
90       2
91       2
92       2
93
94
95       2
96      3+
97       2
98       2
99       2
100      3
101      3
102      3
103      2
104      2
105     3+
106     3+
107      3
108      1
109      2
110      2
111      1
112      2
113      2
114      2
115      1
116     3+
117      2
118     3+
119     3+
120      2
121      1
122      1
123      3
124      3
125      2
126      3
127      2
128      2
129
130      3
131
132      1
133      1
134      1
135      2
136      2
137      1
138      1
139      3
140     3+
141      3
142
143      3
144      2
145      3
146      3
147     3+
148      3
149      1
150      3
151      1
152      3
153      2
154      1
155      3
156      1
157      3
158      3
159      1
160      3
161     3+
162      2
163      2
164      2
165     3+
166
167      1
168      3
169      2
170      3
171      2
172      2
173     3+
174     3+
175     3+
176     3+
177      3
178      2
179      3
180     3+
181
182      3
183      1
184      3
185     3+
186      3
187      3
188      1
189      1
190      1
191     3+
192
193     3+
194      3
195
196      3
197     3+
198      1
199      2
200      3
201      1
202
203      3
204     3+
205      3
206
207      1
208      3
209      1
210      3
211      3
212      3
213      1
214      2
215      2
216     3+
217      3
218      2
219     3+
220      3
221      3
222      3
223      3
224      1
225      1
226      2
227      3
228      3
229     3+
230      3
231      2
232      1
233      2
234      3
235      2
236      3
237     3+
238      3
239      3
240      2
241      3
242      1
243      2
244     3+
245      3
246      2
247      3
248      3
249      2
250      3
251      1
252      3
253      2
254      3
255      3
256      3
257      3
258      2
259     3+
260      2
261      3
262      3
263      3
264      3
265     3+
266     3+
267      2
268      2
269     3+
270      3
271      2
272     3+
273      2
274     3+
275
276      2
277      3
278
279
280
281     3+
282      3
283      2
284      3
285      3
287      3
288      3
289     3+
290     3+
291      2
292     3+
293     3+
294      2
295      3
296      3
297      3
298      2
299      2
300      3
301      3
302      1
303      3
304      1
305      2
306      2
307      3
308     3+
309     3+
310      2
311      3
312      2
313      2
314     3+
315     3+
316      3
317     3+
318      3
319     3+
320      3
321     3+
322     3+
323      2
324      3
325      3
326      2
327      3
328      3
329      1
330      3
331      1
332      2
333      2
334      3
335     3+
336      3
337      2
338     3+
339      3
340      3
341     3+
342      3
343     3+
344     3+
345      3
346     3+
347     3+
348      2
349      1
350      1
351      3
352      2
353      1
354      3
355      3
356     3+
357      2
358      3
359      3
360     3+
361      3
362     3+
363      3
364      2
365      2
366      3
367     3+
368      2
369      2
370      3
371      3
372      2
373      2
374     3+
375      3
376     3+
377     3+
378      1
379      3
380      3
381      2
382     3+
383     3+
384     3+
385     3+
386     3+
387      3
388      3
389     3+
390      3
391     3+
392      2
393      3
394      3
395     3+
396      3
397      2
398      2
399      2
400      3
401      3
402      3
403      2
404     3+
405      2
406      3
407     3+
408      3
409     3+
410      2
411     3+
412     3+
413     3+
414     3+
415      3
416     3+
417      3
418      3
419      1
420      2
421     3+
422     3+
423     3+
424      2
425     3+
426     3+
427     3+
428      2
429      3
430     3+
431      3
432     3+
433      3
434      3
435      3
436      3
437      2
438      3
439      2
440     3+
441      3
442      3
443      3
444     3+
445      2
446     3+
447      3
448      2
449     3+
450      3
451      3
452      3
453     3+
454     3+
455     3+
456     3+
457      3
458     3+
459      3
460      3
461     3+
462      2
463      2
464     3+
465     3+
466     3+
467     3+
468     3+
469     3+
470      2
471      3
472      3
473     3+
474     3+
475      3
476      3
477     3+
478      3
479     3+
480      3
481     3+
482      3
483      3
484      3
485      3
486     3+
487     3+
488     3+
489     3+
490      3
491      3
492      3
493     3+
494     3+
495      3
496      1
497     3+
498     3+
499     3+
500      3
501      2
502     3+
503      3
504      2
505      2
506      3
507      3
508     3+
509     3+
510     3+
511      3
512     3+
513      3
514      3
515     3+
516     3+
517     3+
518     3+
519      2
520     3+
521     3+
522     3+
523      3
524      3
525      2
526     3+
527      3
528      2
529      3
530     3+
531     3+
532     3+
533      3
534      2
535     3+
536      3
537      3
538     3+
539     3+
540      3
541     3+
542      3
543     3+
544     3+
545      2
546      2
547     3+
548     3+
549     3+
550      3
551      2
552      3
553     3+
554     3+
555      2
556      3
557     3+
558      2
559      3
560     3+
561      3
562      1
563      2
564      3
565     3+
566     3+
567     3+
568     3+
569     3+
570     3+
571     3+
572     3+
573      3
574     3+
575      3
576      3
577      2
578      2
579      3
580     3+
581     3+
582     3+
583      3
584     3+
585     3+
586     3+
587     3+
588      3
589      3
590      2
591     3+
592      2
593      2
594     3+
595     3+
596     3+
597     3+
598     3+
599     3+
600     3+
601     3+
602     3+
603      3
604     3+
605      3
606      3
607     3+
608     3+
609     3+
610      3
611      3
612     3+
613     3+
614      1
615     3+
616     3+
617     3+
618      3
619     3+
620      3
621      3
622     3+
623      3
624     3+
625     3+
626     3+
627      3
628      3
629      2
630      3
631      3
632     3+
633      2
634     3+
635     3+
636      3
637     3+
638      3
639      2
640     3+
641      2
642     3+
643     3+
644     3+
645      3
646     3+
647     3+
648     3+
649     3+
650     3+
651     3+
652     3+
653      3
654     3+
655      3
656     3+
657      3
658      2
659      3
660     3+
661      3
662      3
663      3
664     3+
665      3
666      3
667      1
668     3+
669     3+
670     3+
671      3
672      3
673      3
674     3+
675     3+
676      3
677     3+
678      3
679     3+
680      3
681     3+
682      3
683      3
684     3+
685     3+
686     3+
687      2
688      3
689      3
690     3+
691      2
692      3
693      3
694      3
695      2
696      2
697     3+
698     3+
699     3+
700      3
701     3+
702     3+
703      3
704      2
705      3
706      3
707      3
708      3
709     3+
710      3
711     3+
712     3+
713     3+
714     3+
715     3+
716      2
717      3
718      3
719     3+
720     3+
721      2
722      2
723      2
724      2
725      3
726     3+
727      3
728      1
729      3
730      2
731      2
732     3+
733      3
734     3+
735     3+
736     3+
737     3+
738      3
739      3
740     3+
741      2
742      2
743      3
744     3+
745      3
746      2
747     3+
748     3+
749     3+
750      3
751      2
752      3
753      3
754      3
755     3+
756     3+
757     3+
758      3
759     3+
760      3
761     3+
762     3+
763      2
764      2
765      2
766      3
767     3+
768      3
769     3+
770     3+
771      2
772     3+
773     3+
774      2
775      2
776      3
777      3
778     3+
779      3
780      3
781      3
782      3
783      1
784     3+
785      3
786     3+
787     3+
788     3+
789      2
790      3
791      1
792     3+
793     3+
794      3
795      3
796      3
797      3
798      3
799     3+
800      3
801      3
802     3+
803     3+
804      3
805      3
806      3
807      3
808      3
809      2
810      3
811     3+
812      3
813      2
814     3+
815      2
816      3
817      2
818      2
819     3+
820     3+
821      3
822     3+
823      3
824      1
825      2
826      1
827      1
828      2
829      2
830     3+
831     3+
832      3
833     3+
834     3+
835      3
836     3+
837      2
838     3+
839     3+
840      3
841      3
842     3+
843      3
844      3
845     3+
846      3
847      3
848      3
849      3
850      3
851      3
852      3
853     3+
854      3
855     3+
856     3+
857      3
858      3
859      3
860      3
861     3+
862     3+
863      3
864      2
865      3
866      2
867      3
868     3+
869      3
870      2
871      2
872      3
873     3+
874      3
875      2
876      2
877      3
878      2
879     3+
880     3+
881      3
882     3+
883      3
884      1
885      3
886      3
887     3+
888     3+
889     3+
890     3+
891      3
892      2
893     3+
894     3+
895     3+
896      3
897     3+
898     3+
899      3
900      3
901      3
902      3
903      3
904      3
905      2
906      2
907      3
908      3
909      3
910      3
911     3+
912      3
913     3+
914      3
915      2
916      2
917      3
918      1
919      2
920     3+
921      2
922      3
923     3+
924     3+
925      3
926     3+
927      3
928      3
929      2
930      3
931     3+
932      2
933      3
934     3+
935     3+
936      2
937     3+
938     3+
939     3+
940      2
941      2
942     3+
943      3
944      3
945      1
946      1
947     3+
948     3+
949      3
950      2
951      3
952     3+
953     3+
954      2
955      3
956     3+
957     3+
958      3
959      2
960      2
961     3+
962     3+
963      3
964     3+
965     3+
966     3+
967     3+
968      2
969     3+
970     3+
971     3+
972     3+
973     3+
974     3+
975     3+
976      3
977      3
978      3
979      1
980      2
981      2
982      3
983      3
984      3
985     3+
986      2
987      3
988      3
989      3
990      3
991      3
992      2
993      2
994      3
995      3
996     3+
997      3
998      2
999     3+
1000    3+
1001     3
1002    3+
1003    3+
1004    3+
1005     2
1006     3
1007     2
1008     3
1009     3
1010     3
1011     3
1012     3
1013     3
1014     2
1015     2
1016    3+
1017     3
1018    3+
1019    3+
1020    3+
1021     2
1022    3+
1023    3+
1024    3+
1025    3+
1026    3+
1027    3+
1028     2
1029     3
1030     3
1031    3+
1032     2
1033     2
1034    3+
1035     3
1036    3+
1037     3
1038    3+
1039     3
1040    3+
1041    3+
1042    3+
1043     3
1044    3+
1045    3+
1046    3+
1047     3
1048     3
1049     3
1050     2
1051     1
1052     3
1053    3+
1054     3
1055    3+
1056     2
1057     2
1058     3
1059     2
1060     2
1061    3+
1062     3
1063     2
1064     3
1065     2
1066    3+
1067    3+
1068     3
1069     3
1070     3
1071     3
1072     3
1073    3+
1074     2
1075    3+
1076    3+
1077    3+
1078     3
1079    3+
1080     3
1081     3
1082     2
1083    3+
1084     2
1085     2
1086     2
1087     2
1088     1
1089     1
1090     3
1091     3
1092     3
1093    3+
1094    3+
1095    3+
1096    3+
1097     3
1098     1
1099    3+
1100    3+
1101     3
1102    3+
1103     2
1104    3+
1105     2
1106     2
1107    3+
1108    3+
1109    3+
1110     2
1111     2
1112     2
1113    3+
1114     3
1115     3
1116     2
1117     2
1118     2
1119     3
1120     2
1121     1
1122     2
1123    3+
1124    3+
1125     2
1126     2
1127    3+
1128    3+
1129     3
1130    3+
1131    3+
1132     3
1133    3+
1134     1
1135     1
1136     1
1137     1
1138     1
1139     1
1140     1
1141     1
1142     1
1143     3
1144     1
1145     2
1146     2
1147     1
1148     2
1149     1
1150    3+
1151     1
1152     3
1153     1
1154     2
1155     3
1156     2
1157     2
1158     2
1159     2
1160     1
1161     2
1162     2
1163     2
1164     2
1165     2
1166     3
1167     3
1168     3
1169     2
1170     2
1171     3
1172     2
1173     1
1174    3+
1175     3
1176    3+
1177     3
1178     3
1179    3+
1180     2
1181     3
1182    3+
1183     3
1184     3
1185     3
1186     3
1187     3
1188     3
1189     2
1190     3
1191     2
1192     3
1193     3
1194     3
1195    3+
1196    3+
1197     2
1198     2
1199     3
1200     3
1201     3
1202    3+
1203     3
1204     3
1205    3+
1206    3+
1207     3
1208     2
1209     1
1210     1
1211     2
1212    3+
1213     3
1214    3+
1215     3
1216     2
1217     3
1218     3
1219     2
1220     2
1221    3+
1222     1
1223     1
1224     2
1225    3+
1226    3+
1227    3+
1228    3+
1229    3+
1230    3+
1231     3
1232    3+
1233     2
1234     3
1235    3+
1236    3+
1237    3+
1238    3+
1239     3
1240    3+
1241     3
1242    3+
1243     3
1244    3+
1245     3
1246     3
1247     3
1248     3
1249     3
1250     3
1251     3
1252     3
1253     3
1254     3
1255     3
1256     3
1257     3
1258     2
1259     3
1260     1
1261     1
1262     1
1263     1
1264     3
1265     2
1266     3
1267     3
1268     3
1269     3
1270     3
1271     3
1272    3+
1273    3+
1274     2
1275     3
1276    3+
1277    3+
1278     3
1279     3
1280    3+
1281    3+
1282    3+
1283     2
1284     2
1285     2
1286    3+
1287    3+
1288    3+
1289    3+
1290     3
1291     3
1292     2
1293     3
1294     3
1295     3
1296     2
1297     3
1298     2
1299     1
1300     3
1301    3+
1302    3+
1303     3
1304     2
1305     3
1306     2
1307     1
1308     1
1309     1
1310     1
1311     1
1312     1
1313     1
1314     3
1315     3
1316    3+
1317    3+
1318    3+
1319     2
1320    3+
1321    3+
1322    3+
1323     3
1324    3+
1325     2
1326    3+
1327     3
1328     1
1329     3
1330     1
1331     1
1332     1
1333     1
1334     1
1335     1
1336    3+
1337     3
1338     1
1339     2
1340     3
1341     2
1342     3
1343     1
1344    3+
1345     3
1346    3+
1347     3
1348    3+
1349    3+
1350    3+
1351     2
1352    3+
1353    3+
1354    3+
1355    3+
1356     3
1357    3+
1358     3
1359     3
1360     1
1361     3
1362    3+
1363    3+
1364    3+
1365    3+
1366     2
1367    3+
1368     3
1369    3+
1370     3
1371     3
1372    3+
1373     3
1374    3+
1375     2
1376    3+
1377    3+
1378    3+
1379     1
1380     3
1381     3
1382     3
1383     3
1384     3
1385     3
1386     3
1387     3
1388     3
1389     2
1390     3
1391     3
1392     2
1393     3
1394     3
1395     1
1396     3
1397     3
1398    3+
1399     3
1400     3
1401     3
1402     3
1403     3
1404     2
1405     2
1406     2
1407     1
1408     3
1409    3+
1410     2
1411     3
1412     3
1413    3+
1414     3
1415     3
1416    3+
1417     3
1418    3+
1419     1
1420    3+
1421    3+
1422     1
1423     1
1424     3
1425     3
1426     3
1427    3+
1428     3
1429     3
1430     3
1431    3+
1432     3
1433     2
1434     3
1435    3+
1436     3
1437     3
1438     3
1439     3
1440     2
1441     2
1442     3
1443     2
1444     3
1445     3
1446    3+
1447     3
1448    3+
1449     3
1450     3
1451     2
1452     3
1453     3
1454     2
1455    3+
1456    3+
1457    3+
1458     3
1459    3+
1460    3+
1461    3+
1462     2
1463     2
1464     3
1465     3
1466     3
1467    3+
1468     3
1469     3
1470     2
1471     3
1472    3+
1473     3
1474     3
1475     3
1476    3+
1477    3+
1478    3+
1479    3+
1480     3
1481     3
1482     3
1483     3
1484     3
1485    3+
1486     3
1487    3+
1488    3+
1489    3+
1490     3
1491    3+
1492     3
1493     3
1494     3
1495     3
1496    3+
1497    3+
1498     3
1499    3+
1500    3+
1501    3+
1502    3+
1503    3+
1504    3+
1505     2
1506     3
1507     2
1508    3+
1509    3+
1510     2
1511     3
1512    3+
1513     3
1514    3+
1515    3+
1516     3
1517     2
1518    3+
1519    3+
1520     3
1521     3
1522     3
1523     3
1524     3
1525     3
1526     3
1527     3
1528     3
1529     3
1530     3
1531     3
1532     3
1533     3
1534     3
1535     3
1536     3
1537     3
1538     3
1539    3+
1540    3+
1541    3+
1542     3
1543     3
1544    3+
1545    3+
1546     2
1547    3+
1548     2
1549     2
1550     3
1551     3
1552     3
1553    3+
1554    3+
1555    3+
1556     1
1557     1
1558    3+
1559     2
1560    3+
1561    3+
1562     3
1563    3+
1564    3+
1565    3+
1566    3+
1567    3+
1568    3+
1569    3+
1570    3+
1571    3+
1572     3
1573    3+
1574    3+
1575     3
1576    3+
1577     3
1578    3+
1579     3
1580    3+
1581     3
1582     3
1583     3
1584    3+
1585    3+
1586    3+
1587    3+
1588     2
1589     2
1590    3+
1591     2
1592    3+
1593     2
1594     3
1595     3
1596     3
1597     3
1598     1
1599     1
1600     2
1601     3
1602     2
1603     2
1604     2
1605     2
1606     2
1607     2
1608     2
1609    3+
1610    3+
1611     3
1612    3+
1613    3+
1614     3
1615    3+
1616    3+
1617     2
1618     3
1619     2
1620     2
1621    3+
1622     3
1623     3
1624     3
1625     3
1626     3
1627    3+
1628    3+
1629    3+
1630    3+
1631     3
1632    3+
1633     2
1634     2
1635     3
1636     3
1637     3
1638    3+
1639     2
1640     2
1641     3
1642     3
1643    3+
1644     2
1646    3+
1647     2
1648     2
1649     2
1650     3
1651    3+
1652     2
1653     3
1654    3+
1655    3+
1656     2
1657     3
1658     3
1659    3+
1660    3+
1661    3+
1662    3+
1663    3+
1664    3+
1665     3
1666    3+
1667     3
1668     3
1669    3+
1670     3
1671    3+
1672    3+
1673     3
1674    3+
1675    3+
1676     3
1677    3+
1678    3+
1679    3+
1680    3+
1681     3
1682    3+
1683     3
1684     3
1685     2
1686    3+
1687     1
1688     2
1689     2
1690    3+
1691    3+
1692    3+
1693    3+
1694    3+
1695    3+
1696    3+
1697     2
1698    3+
1699     2
1700     2
1701     2
1702    3+
1703    3+
1704     3
1705     3
1706    3+
1707    3+
1708    3+
1709     2
1710     2
1711     1
1712     1
1713     2
1714     1
1715     2
1716     2
1717    3+
1718    3+
1719     1
1720     1
1721     3
1722     3
1723     2
1724     1
1725     2
1726     2
1727     2
1728     2
1729     1
1730     2
1731     2
1732     2
1733     2
1734     3
1735    3+
1736    3+
1737     2
1738     2
1739    3+
1740    3+
1741     2
1742    3+
1743    3+
1744    3+
1745     3
1746    3+
1747    3+
1748    3+
1749    3+
1750     3
1751     2
1752     3
1753    3+
1754    3+
1755    3+
1756    3+
1757    3+
1758     3
1759     3
1760     3
1761     3
1762     2
1763     2
1764     2
1765    3+
1766     1
1767     2
1768    3+
1769     2
1770     2
1771     2
1772     2
1773     2
1774     1
1775    3+
1776     1
1777     1
1778     1
1779     2
1780     2
1781     2
1782     2
1783     3
1784    3+
1785    3+
1786    3+
1787     3
1788    3+
1789    3+
1790    3+
1791     2
1792    3+
1793    3+
1794    3+
1795     2
1796     2
1797     2
1798     2
1799     2
1800     2
1801     2
1802     3
1803     3
1804     3
1805     3
1806     3
1807     2
1808    3+
1809     1
1810     3
1811     3
1812    3+
1813     3
1814     3
1815     2
1816     3
1817     2
1818     2
1819     3
1820     3
1821    3+
1822     3
1823     3
1824    3+
1825     3
1826     1
1827    3+
1828     3
1829     2
1830     3
1831    3+
1832     1

In [139]:
df.head()

,property_name,society,price,persf_area,areaWithType,bedroom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [140]:
df = df.drop(columns = ["rating","property_id"])

In [141]:
df.head()

,property_name,society,price,persf_area,areaWithType,bedroom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te..."
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN

In [142]:
df["additionalRoom"]=df["additionalRoom"].str.lower()

In [143]:
df["additionalRoom"].value_counts()

servant room                                     629
study room                                       232
others                                           179
pooja room                                       132
study room,servant room                           81
store room                                        76
pooja room,servant room                           60
servant room,others                               52
servant room,pooja room                           30
study room,others                                 27
pooja room,study room,servant room,others         25
pooja room,study room,servant room                24
servant room,store room                           19
pooja room,study room                             13
pooja room,study room,servant room,store room     12
study room,pooja room                              8
servant room,study room                            8
study room,servant room,store room                 7
pooja room,store room                              6
pooja room,others                                  6
others,servant room                                6
servant room,study room,pooja room,store room      6
pooja room,servant room,others                     6
study room,servant room,others                     5
pooja room,store room,study room,servant room      4
pooja room,study room,store room                   4
servant room,pooja room,study room,store room      3
study room,pooja room,store room                   3
store room,servant room                            3
servant room,study room,store room                 2
pooja room,study room,others                       2
study room,pooja room,servant room                 2
servant room,others,store room,pooja room          2
servant room,others,pooja room                     2
study room,servant room,pooja room,store room      2
others,study room                                  1
servant room,study room,others                     1
servant room,pooja room,study room                 1
servant room,study room,pooja room                 1
store room,pooja room,servant room                 1
servant room,pooja room,store room,study room      1
study room,store room                              1
store room,study room                              1
servant room,pooja room,store room                 1
study room,servant room,store room,pooja room      1
study room,servant room,pooja room                 1
pooja room,servant room,study room,store room      1
pooja room,study room,store room,servant room      1
store room,pooja room                              1
Name: additionalRoom, dtype: int64

In [144]:
df["additionalRoom"]=df["additionalRoom"].fillna("not av")

In [145]:
df["additionalRoom"].value_counts()

not av                                           1305
servant room                                      629
study room                                        232
others                                            179
pooja room                                        132
study room,servant room                            81
store room                                         76
pooja room,servant room                            60
servant room,others                                52
servant room,pooja room                            30
study room,others                                  27
pooja room,study room,servant room,others          25
pooja room,study room,servant room                 24
servant room,store room                            19
pooja room,study room                              13
pooja room,study room,servant room,store room      12
study room,pooja room                               8
servant room,study room                             8
study room,servant room,store room                  7
pooja room,store room                               6
pooja room,others                                   6
others,servant room                                 6
servant room,study room,pooja room,store room       6
pooja room,servant room,others                      6
study room,servant room,others                      5
pooja room,store room,study room,servant room       4
pooja room,study room,store room                    4
servant room,pooja room,study room,store room       3
study room,pooja room,store room                    3
store room,servant room                             3
servant room,study room,store room                  2
pooja room,study room,others                        2
study room,pooja room,servant room                  2
servant room,others,store room,pooja room           2
servant room,others,pooja room                      2
study room,servant room,pooja room,store room       2
others,study room                                   1
servant room,study room,others                      1
servant room,pooja room,study room                  1
servant room,study room,pooja room                  1
store room,pooja room,servant room                  1
servant room,pooja room,store room,study room       1
study room,store room                               1
store room,study room                               1
servant room,pooja room,store room                  1
study room,servant room,store room,pooja room       1
study room,servant room,pooja room                  1
pooja room,servant room,study room,store room       1
pooja room,study room,store room,servant room       1
store room,pooja room                               1
Name: additionalRoom, dtype: int64

In [146]:
df.head(3)

,property_name,society,price,persf_area,areaWithType,bedroom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1,not av,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1,not av,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3,not av,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."

In [147]:
df["floorNum"]=df["floorNum"].str.lower()

In [148]:
df["floorNum"]=df["floorNum"].str.split().str.get(0).replace("ground","0").replace("basement","-1").str.replace('lower','0').str.extract(r"(\d+)")

In [149]:
df["facing"].value_counts()

North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: facing, dtype: int64

In [150]:
df["facing"].isnull().sum()

874

In [151]:
df[df["facing"].isnull()].sample(3)

,property_name,society,price,persf_area,areaWithType,bedroom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
2660,4 BHK Flat in Sector 99 Gurgaon,vatika sovereign park,3.25,9672.0,Super Built up area 3360(312.15 sq.m.),4.0,4.0,3+,servant room,"Sector 99 Gurgaon, Gurgaon, Haryana",2,NaN,Within 3 months,"['The Esplanade Mall', 'Dwarka Expressway', 'K...",Garden facing on the second floor,NaN,"['Security / Fire Alarm', 'Intercom Facility',..."
344,3 BHK Flat in Sector 108 Gurgaon,experion the heartsong,1.36,6542.0,Super Built up area 1758(163.32 sq.m.)Carpet a...,3.0,2.0,3+,"study room,servant room","Sector 108 Gurgaon, Gurgaon, Haryana",2,NaN,1 to 5 Year Old,"['Galleria 108 Mall', 'Dwarka Expressway', 'Ce...",3bhk 3baths residential apartment for sale in ...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Lift(s)', 'Centrally Air Conditioned', 'Main..."
2074,3 BHK Flat in Chakkarpur,sahara grace,4.30,12420.0,Super Built up area 3462.01(321.63 sq.m.),3.0,4.0,3,"servant room,store room","Chakkarpur, Gurgaon, Haryana",5,NaN,10+ Year Old,"['Mg road metro station', 'Sikandarpur metro s...","Very well maintained, excellent layout and bea...","['4 Wardrobe', '4 Geyser', '5 AC', 'No Bed', '...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ..."

In [152]:
df["facing"]=df["facing"].fillna("NA")

In [153]:
area=round(df["price"]*10000000/df["persf_area"],2)

In [154]:
df.insert(4,"area",area)

In [155]:
df.head()

,property_name,society,price,persf_area,area,areaWithType,bedroom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,900.00,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1,not av,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,650.03,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1,not av,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,595.06,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3,not av,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,1200.00,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te..."
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,1345.12,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN

In [161]:
#df.insert(loc=1,column='property_type',value='flat')

In [159]:
df.head()

,property_name,property_type,society,price,persf_area,area,areaWithType,bedroom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.00,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1,not av,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.03,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1,not av,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.06,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3,not av,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.00,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te..."
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.12,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN

In [157]:
df.to_csv("flats_clean.csv")

In [158]:
df.shape

(2997, 19)